/*
 * 롤토체스 챔피언 / 특성 데이터
 * 원본 파이썬 스크립트(tft.py, tft2.py)의 데이터를 그대로 옮긴 것입니다.
 * 세트가 바뀌면 이 파일만 수정하면 됩니다.
 */

const CHAMPIONS = {
  "니달리": { traits: ["니트로", "증.폭."], cost: 1 },
  "모르가나": { traits: ["신성기업", "다이나모"], cost: 1 },
  "문도 박사": { traits: ["거리의 악마", "난동꾼", "학살자"], cost: 1 },
  "바이": { traits: ["사이퍼", "선봉대"], cost: 1 },
  "뽀삐": { traits: ["사이버보스", "요새"], cost: 1 },
  "사일러스": { traits: ["동물특공대", "선봉대"], cost: 1 },
  "샤코": { traits: ["범죄 조직", "학살자"], cost: 1 },
  "세라핀": { traits: ["동물특공대", "기술광"], cost: 1 },
  "알리스타": { traits: ["황금 황소", "난동꾼"], cost: 1 },
  "자이라": { traits: ["거리의 악마", "기술광"], cost: 1 },
  "잭스": { traits: ["엑소테크", "요새"], cost: 1 },
  "코그모": { traits: ["폭발봇", "속사포"], cost: 1 },
  "킨드레드": { traits: ["니트로", "사격수", "속사포"], cost: 1 },
  "그레이브즈": { traits: ["황금 황소", "처형자"], cost: 2 },
  "나피리": { traits: ["엑소테크", "증.폭."], cost: 2 },
  "다리우스": { traits: ["범죄 조직", "난동꾼"], cost: 2 },
  "라아스트": { traits: ["신성기업", "선봉대"], cost: 2 },
  "르블랑": { traits: ["사이퍼", "기술광"], cost: 2 },
  "베이가": { traits: ["사이버보스", "기술광"], cost: 2 },
  "베인": { traits: ["동물특공대", "학살자"], cost: 2 },
  "쉬바나": { traits: ["니트로", "기술광", "요새"], cost: 2 },
  "스카너": { traits: ["폭발봇", "선봉대"], cost: 2 },
  "에코": { traits: ["거리의 악마", "책략가"], cost: 2 },
  "일라오이": { traits: ["동물특공대", "요새"], cost: 2 },
  "진": { traits: ["엑소테크", "다이나모"], cost: 2 },
  "트위스티드 페이트": { traits: ["범죄 조직", "속사포"], cost: 2 },
  "갈리오": { traits: ["사이퍼", "요새"], cost: 3 },
  "그라가스": { traits: ["신성기업", "난동꾼"], cost: 3 },
  "드레이븐": { traits: ["사이퍼", "속사포"], cost: 3 },
  "렝가": { traits: ["거리의 악마", "처형자"], cost: 3 },
  "모데카이저": { traits: ["엑소테크", "기술광", "난동꾼"], cost: 3 },
  "바루스": { traits: ["엑소테크", "처형자"], cost: 3 },
  "브라움": { traits: ["범죄 조직", "선봉대"], cost: 3 },
  "세나": { traits: ["신성기업", "학살자"], cost: 3 },
  "엘리스": { traits: ["니트로", "다이나모"], cost: 3 },
  "유미": { traits: ["동물특공대", "증.폭.", "책략가"], cost: 3 },
  "자르반 4세": { traits: ["황금 황소", "선봉대", "학살자"], cost: 3 },
  "징크스": { traits: ["거리의 악마", "사격수"], cost: 3 },
  "피들스틱": { traits: ["폭발봇", "기술광"], cost: 3 },
  "니코": { traits: ["거리의 악마", "책략가"], cost: 4 },
  "레오나": { traits: ["동물특공대", "선봉대"], cost: 4 },
  "미스 포츈": { traits: ["범죄 조직", "다이나모"], cost: 4 },
  "벡스": { traits: ["신성기업", "처형자"], cost: 4 },
  "브랜드": { traits: ["거리의 악마", "기술광"], cost: 4 },
  "세주아니": { traits: ["엑소테크", "요새"], cost: 4 },
  "아펠리오스": { traits: ["황금 황소", "사격수"], cost: 4 },
  "애니": { traits: ["황금 황소", "증.폭."], cost: 4 },
  "자야": { traits: ["동물특공대", "사격수"], cost: 4 },
  "제드": { traits: ["사이퍼", "학살자"], cost: 4 },
  "제리": { traits: ["엑소테크", "속사포"], cost: 4 },
  "직스": { traits: ["사이버보스", "책략가"], cost: 4 },
  "초가스": { traits: ["폭발봇", "난동꾼"], cost: 4 },
  "가렌": { traits: ["네트워크의 신"], cost: 5 },
  "레넥톤": { traits: ["신성기업", "군주", "요새"], cost: 5 },
  "비에고": { traits: ["황금 황소", "영혼 살해자", "기술광"], cost: 5 },
  "사미라": { traits: ["거리의 악마", "증.폭."], cost: 5 },
  "오로라": { traits: ["동물특공대", "다이나모"], cost: 5 },
  "우르곳": { traits: ["폭발봇", "처형자"], cost: 5 },
  "자크": { traits: ["바이러스"], cost: 5 },
  "코부코": { traits: ["사이버보스", "난동꾼"], cost: 5 },
};

const TRAITS = {
  "기술광": { breakpoints: [2, 4, 6, 8] },
  "난동꾼": { breakpoints: [2, 4, 6] },
  "다이나모": { breakpoints: [2, 3, 4] },
  "사격수": { breakpoints: [2, 4] },
  "선봉대": { breakpoints: [2, 4, 6] },
  "속사포": { breakpoints: [2, 4, 6] },
  "요새": { breakpoints: [2, 4, 6] },
  "증.폭.": { breakpoints: [2, 3, 4, 5] },
  "책략가": { breakpoints: [2, 3, 4, 5] },
  "처형자": { breakpoints: [2, 3, 4, 5] },
  "학살자": { breakpoints: [2, 4, 6] },
  "거리의 악마": { breakpoints: [3, 5, 7, 10] },
  "군주": { breakpoints: [1] },
  "네트워크의 신": { breakpoints: [1] },
  "니트로": { breakpoints: [3, 4] },
  "엑소테크": { breakpoints: [3, 5, 7, 10] },
  "사이버보스": { breakpoints: [2, 3, 4] },
  "신성기업": { breakpoints: [1, 2, 3, 4, 5, 6, 7] },
  "범죄 조직": { breakpoints: [3, 5, 7] },
  "동물특공대": { breakpoints: [3, 5, 7, 10] },
  "폭발봇": { breakpoints: [2, 4, 6] },
  "사이퍼": { breakpoints: [3, 4, 5] },
  "황금 황소": { breakpoints: [2, 4, 6] },
  "바이러스": { breakpoints: [1] },
  "영혼 살해자": { breakpoints: [1] },
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = { CHAMPIONS, TRAITS };
}
